name: development_workflow
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Running linting job to ensure code follows formatting standards
        run: |
            echo "This job will be for linting"

  app_integration:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Running code integration with all apps related to forge atlassian
        run: |
            echo "This job will be for code integration"

  test:
    runs-on: ubuntu-latest
    needs: [lint, app_integration]
    steps:
      - name: Running tests against test deployment
        run: |
            echo "This job will be for testing deployment"
